import { env } from "cloudflare:workers";
import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { products } from "../../../../db/schema";
import { cookieValue, mtop } from "../../../../lib/xianyu";
export const dynamic="force-dynamic";
type RuntimeEnv={XIANYU_COOKIE?:string};
type Card={id?:string|number;title?:string;itemStatus?:string;priceInfo?:{price?:string|number};picInfo?:{picUrl?:string}};
function extract(card:Card){return {itemId:String(card.id||""),title:String(card.title||"未命名商品"),priceCents:Math.round(Number(card.priceInfo?.price||0)*100),status:String(card.itemStatus)==="1"?"offline":"published",image:String(card.picInfo?.picUrl||"")}}
export async function GET(){try{return Response.json({items:await getDb().select().from(products).where(eq(products.status,"published")).orderBy(desc(products.updatedAt))})}catch(e){return Response.json({error:e instanceof Error?e.message:"读取失败"},{status:500})}}
export async function POST(){const cookie=(env as unknown as RuntimeEnv).XIANYU_COOKIE;if(!cookie)return Response.json({error:"尚未配置闲鱼 Cookie"},{status:503});try{const userId=cookieValue(cookie,"unb");if(!userId)throw new Error("Cookie 缺少账号字段 unb");let page=1,synced=0;const seen=new Set<string>();while(page<=10){const raw=await mtop(cookie,"mtop.idle.web.xyh.item.list",{needGroupInfo:true,pageNumber:page,userId,pageSize:20},{spm:"a21ybx.item.0.0"});const data=raw.data||{},cards:Card[]=[];const top=data.topItem as {cardData?:Card}|undefined;if(page===1&&top)cards.push(top.cardData||top as Card);for(const wrap of (data.cardList as Array<{cardData?:Card}>||[]))cards.push(wrap.cardData||wrap as Card);let added=0;for(const card of cards){const item=extract(card);if(!item.itemId||seen.has(item.itemId))continue;seen.add(item.itemId);added++;const now=new Date().toISOString();await getDb().insert(products).values({title:item.title,priceCents:item.priceCents,imagesJson:JSON.stringify(item.image?[item.image]:[]),status:item.status,xianyuItemId:item.itemId,updatedAt:now}).onConflictDoUpdate({target:products.xianyuItemId,set:{title:item.title,priceCents:item.priceCents,imagesJson:JSON.stringify(item.image?[item.image]:[]),status:item.status,lastError:null,updatedAt:now}});synced++}if(!added||!data.nextPage)break;page++}return Response.json({success:true,synced})}catch(e){return Response.json({error:e instanceof Error?e.message:"同步失败"},{status:502})}}
